[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "LMCAS TaBaCCo Documentation"

[preprocessor.asciinema]
command = "python3 ./mdbook-asciinema.py"
renderers = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"

[output.html]
additional-css = ["asciinema-player.css"]
additional-js = ["asciinema-player.min.js", "mermaid.min.js",  "mermaid-init.js"]

[output.html.playground]
copyable = false

[output.linkcheck]
follow-web-links = false
