#!/bin/bash
echo Waiting for container $1

thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd -P "$( dirname "$SOURCE" )" && /bin/pwd )"
echo thisdir is $thisdir

${thisdir}/../prt/logwatcher.pl -e -d $1 \
        -p "container is up"\
        -q "error" \
        -q "Error"
