# SPDX-FileCopyrightText: 2022-2024 Smart Information Flow Technologies
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# This file was @generated by crate2nix 0.10.0 with the command:
#   "generate"
# See https://github.com/kolloch/crate2nix for more info.

{ nixpkgs ? <nixpkgs>, pkgs ? import nixpkgs { config = { }; }, lib ? pkgs.lib
, stdenv ? pkgs.stdenv, buildRustCrateForPkgs ? if buildRustCrate != null then
  lib.warn
  "crate2nix: Passing `buildRustCrate` as argument to Cargo.nix is deprecated. If you don't customize `buildRustCrate`, replace `callPackage ./Cargo.nix {}` by `import ./Cargo.nix { inherit pkgs; }`, and if you need to customize `buildRustCrate`, use `buildRustCrateForPkgs` instead."
  (_: buildRustCrate)
else
  pkgs:
  pkgs.buildRustCrate
  # Deprecated
, buildRustCrate ? null
  # This is used as the `crateOverrides` argument for `buildRustCrate`.
, defaultCrateOverrides ? pkgs.defaultCrateOverrides
  # The features to enable for the root_crate or the workspace_members.
, rootFeatures ? [
  "default"
]
# If true, throw errors instead of issueing deprecation warnings.
, strictDeprecation ? false
  # Used for conditional compilation based on CPU feature detection.
, targetFeatures ? [ ]
  # Whether to perform release builds: longer compile times, faster binaries.
, release ? true
  # Additional crate2nix configuration if it exists.
, crateConfig ? if builtins.pathExists ./crate-config.nix then
  pkgs.callPackage ./crate-config.nix { }
else
  { } }:

rec {
  #
  # "public" attributes that we attempt to keep stable with new versions of crate2nix.
  #

  rootCrate = rec {
    packageId = "instrumentation-parent";

    # Use this attribute to refer to the derivation building your root crate package.
    # You can override the features with rootCrate.build.override { features = [ "default" "feature1" ... ]; }.
    build = internal.buildRustCrateWithFeatures { inherit packageId; };

    # Debug support which might change between releases.
    # File a bug if you depend on any for non-debug work!
    debug = internal.debugCrate { inherit packageId; };
  };
  # Refer your crate build derivation by name here.
  # You can override the features with
  # workspaceMembers."${crateName}".build.override { features = [ "default" "feature1" ... ]; }.
  workspaceMembers = {
    "instrumentation-parent" = rec {
      packageId = "instrumentation-parent";
      build = internal.buildRustCrateWithFeatures {
        packageId = "instrumentation-parent";
      };

      # Debug support which might change between releases.
      # File a bug if you depend on any for non-debug work!
      debug = internal.debugCrate { inherit packageId; };
    };
  };

  # A derivation that joins the outputs of all workspace members together.
  allWorkspaceMembers = pkgs.symlinkJoin {
    name = "all-workspace-members";
    paths = let members = builtins.attrValues workspaceMembers;
    in builtins.map (m: m.build) members;
  };

  #
  # "internal" ("private") attributes that may change in every new version of crate2nix.
  #

  internal = rec {
    # Build and dependency information for crates.
    # Many of the fields are passed one-to-one to buildRustCrate.
    #
    # Noteworthy:
    # * `dependencies`/`buildDependencies`: similar to the corresponding fields for buildRustCrate.
    #   but with additional information which is used during dependency/feature resolution.
    # * `resolvedDependencies`: the selected default features reported by cargo - only included for debugging.
    # * `devDependencies` as of now not used by `buildRustCrate` but used to
    #   inject test dependencies into the build

    crates = {
      "anyhow" = rec {
        crateName = "anyhow";
        version = "1.0.56";
        edition = "2018";
        sha256 = "09rar14hn9xmafjrjhfxkngmp57gk91pqpckvrq0hbhjx5di6qa3";
        authors = [ "David Tolnay <dtolnay@gmail.com>" ];
        features = {
          "backtrace" = [ "dep:backtrace" ];
          "default" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "atty" = rec {
        crateName = "atty";
        version = "0.2.14";
        edition = "2015";
        sha256 = "1s7yslcs6a28c5vz7jwj63lkfgyx8mx99fdirlhi9lbhhzhrpcyr";
        authors = [ "softprops <d.tangren@gmail.com>" ];
        dependencies = [
          {
            name = "hermit-abi";
            packageId = "hermit-abi";
            target = { target, features }: (target."os" == "hermit");
          }
          {
            name = "libc";
            packageId = "libc";
            usesDefaultFeatures = false;
            target = { target, features }: (target."unix" or false);
          }
          {
            name = "winapi";
            packageId = "winapi";
            target = { target, features }: (target."windows" or false);
            features =
              [ "consoleapi" "processenv" "minwinbase" "minwindef" "winbase" ];
          }
        ];

      };
      "autocfg" = rec {
        crateName = "autocfg";
        version = "1.1.0";
        edition = "2015";
        sha256 = "1ylp3cb47ylzabimazvbz9ms6ap784zhb6syaz6c1jqpmcmq0s6l";
        authors = [ "Josh Stone <cuviper@gmail.com>" ];

      };
      "bitflags" = rec {
        crateName = "bitflags";
        version = "1.3.2";
        edition = "2018";
        sha256 = "12ki6w8gn1ldq7yz9y680llwk5gmrhrzszaa17g1sbrw2r2qvwxy";
        authors = [ "The Rust Project Developers" ];
        features = {
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "rustc-dep-of-std" = [ "core" "compiler_builtins" ];
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "bstr" = rec {
        crateName = "bstr";
        version = "0.2.17";
        edition = "2018";
        sha256 = "08rjbhysy6gg27db2h3pnhvr2mlr5vkj797i9625kwg8hgrnjdds";
        authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
        dependencies = [
          {
            name = "lazy_static";
            packageId = "lazy_static";
            optional = true;
          }
          {
            name = "memchr";
            packageId = "memchr";
            usesDefaultFeatures = false;
          }
          {
            name = "regex-automata";
            packageId = "regex-automata";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "serde";
            packageId = "serde";
            optional = true;
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "default" = [ "std" "unicode" ];
          "lazy_static" = [ "dep:lazy_static" ];
          "regex-automata" = [ "dep:regex-automata" ];
          "serde" = [ "dep:serde" ];
          "serde1" = [ "std" "serde1-nostd" "serde/std" ];
          "serde1-nostd" = [ "serde" ];
          "std" = [ "memchr/std" ];
          "unicode" = [ "lazy_static" "regex-automata" ];
        };
        resolvedDefaultFeatures = [
          "default"
          "lazy_static"
          "regex-automata"
          "serde"
          "serde1"
          "serde1-nostd"
          "std"
          "unicode"
        ];
      };
      "cc" = rec {
        crateName = "cc";
        version = "1.0.73";
        edition = "2018";
        crateBin = [ ];
        sha256 = "04ccylrjq94jssh8f7d7hxv64gs9f1m1jrsxb7wqgfxk4xljmzrg";
        authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
        features = {
          "jobserver" = [ "dep:jobserver" ];
          "parallel" = [ "jobserver" ];
        };
      };
      "cfg-if" = rec {
        crateName = "cfg-if";
        version = "1.0.0";
        edition = "2018";
        sha256 = "1za0vb97n4brpzpv8lsbnzmq5r8f2b0cpqqr0sy8h5bn751xxwds";
        authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
        features = {
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "rustc-dep-of-std" = [ "core" "compiler_builtins" ];
        };
      };
      "chrono" = rec {
        crateName = "chrono";
        version = "0.4.19";
        edition = "2015";
        sha256 = "0wyfl6c00vhfl562spnfcna3zkw8jqvcp652m9iskhl8j26dc2k7";
        authors = [
          "Kang Seonghoon <public+rust@mearie.org>"
          "Brandon W Maister <quodlibetor@gmail.com>"
        ];
        dependencies = [
          {
            name = "libc";
            packageId = "libc";
            optional = true;
          }
          {
            name = "num-integer";
            packageId = "num-integer";
            usesDefaultFeatures = false;
          }
          {
            name = "num-traits";
            packageId = "num-traits";
            usesDefaultFeatures = false;
          }
          {
            name = "time";
            packageId = "time";
            optional = true;
          }
          {
            name = "winapi";
            packageId = "winapi";
            optional = true;
            target = { target, features }: (target."windows" or false);
            features = [ "std" "minwinbase" "minwindef" "timezoneapi" ];
          }
        ];
        features = {
          "clock" = [ "libc" "std" "winapi" ];
          "default" = [ "clock" "std" "oldtime" ];
          "js-sys" = [ "dep:js-sys" ];
          "libc" = [ "dep:libc" ];
          "oldtime" = [ "time" ];
          "pure-rust-locales" = [ "dep:pure-rust-locales" ];
          "rustc-serialize" = [ "dep:rustc-serialize" ];
          "serde" = [ "dep:serde" ];
          "time" = [ "dep:time" ];
          "unstable-locales" = [ "pure-rust-locales" "alloc" ];
          "wasm-bindgen" = [ "dep:wasm-bindgen" ];
          "wasmbind" = [ "wasm-bindgen" "js-sys" ];
          "winapi" = [ "dep:winapi" ];
        };
        resolvedDefaultFeatures =
          [ "clock" "default" "libc" "oldtime" "std" "time" "winapi" ];
      };
      "clap" = rec {
        crateName = "clap";
        version = "3.2.7";
        edition = "2021";
        crateBin = [ ];
        sha256 = "056gdrypgcs1dv8aj50sccdij4lv4013516vfx8v8ixj9ckicysv";
        dependencies = [
          {
            name = "atty";
            packageId = "atty";
            optional = true;
          }
          {
            name = "bitflags";
            packageId = "bitflags";
          }
          {
            name = "clap_derive";
            packageId = "clap_derive";
            optional = true;
          }
          {
            name = "clap_lex";
            packageId = "clap_lex";
          }
          {
            name = "indexmap";
            packageId = "indexmap";
          }
          {
            name = "once_cell";
            packageId = "once_cell";
            optional = true;
          }
          {
            name = "strsim";
            packageId = "strsim";
            optional = true;
          }
          {
            name = "termcolor";
            packageId = "termcolor";
            optional = true;
          }
          {
            name = "textwrap";
            packageId = "textwrap";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "atty" = [ "dep:atty" ];
          "backtrace" = [ "dep:backtrace" ];
          "cargo" = [ "once_cell" ];
          "clap_derive" = [ "dep:clap_derive" ];
          "color" = [ "atty" "termcolor" ];
          "debug" = [ "clap_derive/debug" "backtrace" ];
          "default" = [ "std" "color" "suggestions" ];
          "deprecated" = [ "clap_derive/deprecated" ];
          "derive" = [ "clap_derive" "once_cell" ];
          "once_cell" = [ "dep:once_cell" ];
          "regex" = [ "dep:regex" ];
          "std" = [ "indexmap/std" ];
          "strsim" = [ "dep:strsim" ];
          "suggestions" = [ "strsim" ];
          "termcolor" = [ "dep:termcolor" ];
          "terminal_size" = [ "dep:terminal_size" ];
          "unicase" = [ "dep:unicase" ];
          "unicode" = [ "textwrap/unicode-width" "unicase" ];
          "unstable-doc" = [
            "derive"
            "cargo"
            "wrap_help"
            "yaml"
            "env"
            "unicode"
            "regex"
            "unstable-replace"
            "unstable-grouped"
          ];
          "unstable-v4" = [ "clap_derive/unstable-v4" "deprecated" ];
          "wrap_help" = [ "terminal_size" "textwrap/terminal_size" ];
          "yaml" = [ "yaml-rust" ];
          "yaml-rust" = [ "dep:yaml-rust" ];
        };
        resolvedDefaultFeatures = [
          "atty"
          "clap_derive"
          "color"
          "default"
          "derive"
          "once_cell"
          "std"
          "strsim"
          "suggestions"
          "termcolor"
        ];
      };
      "clap_derive" = rec {
        crateName = "clap_derive";
        version = "3.2.7";
        edition = "2021";
        sha256 = "00prk3kkk4fi5aavlpa10d9akrx3cjkfcndrhmxzl6kf6y3z36vm";
        procMacro = true;
        dependencies = [
          {
            name = "heck";
            packageId = "heck";
          }
          {
            name = "proc-macro-error";
            packageId = "proc-macro-error";
          }
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
            features = [ "full" ];
          }
        ];
        features = {
          "raw-deprecated" = [ "deprecated" ];
          "unstable-v4" = [ "deprecated" ];
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "clap_lex" = rec {
        crateName = "clap_lex";
        version = "0.2.4";
        edition = "2021";
        sha256 = "1ib1a9v55ybnaws11l63az0jgz5xiy24jkdgsmyl7grcm3sz4l18";
        dependencies = [{
          name = "os_str_bytes";
          packageId = "os_str_bytes";
          usesDefaultFeatures = false;
          features = [ "raw_os_str" ];
        }];

      };
      "hashbrown" = rec {
        crateName = "hashbrown";
        version = "0.12.1";
        edition = "2021";
        sha256 = "1hycsz4nbnxcma1lngl66q7hlrwn1scdqdj4jqghiw5bk3w4q3fv";
        authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
        features = {
          "ahash" = [ "dep:ahash" ];
          "ahash-compile-time-rng" = [ "ahash/compile-time-rng" ];
          "alloc" = [ "dep:alloc" ];
          "bumpalo" = [ "dep:bumpalo" ];
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "default" = [ "ahash" "inline-more" ];
          "rayon" = [ "dep:rayon" ];
          "rustc-dep-of-std" = [
            "nightly"
            "core"
            "compiler_builtins"
            "alloc"
            "rustc-internal-api"
          ];
          "serde" = [ "dep:serde" ];
        };
        resolvedDefaultFeatures = [ "raw" ];
      };
      "heck" = rec {
        crateName = "heck";
        version = "0.4.0";
        edition = "2018";
        sha256 = "1ygphsnfwl2xpa211vbqkz1db6ri1kvkg8p8sqybi37wclg7fh15";
        authors = [ "Without Boats <woboats@gmail.com>" ];
        features = {
          "unicode" = [ "unicode-segmentation" ];
          "unicode-segmentation" = [ "dep:unicode-segmentation" ];
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "hermit-abi" = rec {
        crateName = "hermit-abi";
        version = "0.1.19";
        edition = "2018";
        sha256 = "0cxcm8093nf5fyn114w8vxbrbcyvv91d4015rdnlgfll7cs6gd32";
        authors = [ "Stefan Lankes" ];
        dependencies = [{
          name = "libc";
          packageId = "libc";
          usesDefaultFeatures = false;
        }];
        features = {
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "rustc-dep-of-std" = [
            "core"
            "compiler_builtins/rustc-dep-of-std"
            "libc/rustc-dep-of-std"
          ];
        };
        resolvedDefaultFeatures = [ "default" ];
      };
      "indexmap" = rec {
        crateName = "indexmap";
        version = "1.9.1";
        edition = "2021";
        sha256 = "07nli1wcz7m81svvig8l5j6vjycjnv9va46lwblgy803ffbmm8qh";
        dependencies = [{
          name = "hashbrown";
          packageId = "hashbrown";
          usesDefaultFeatures = false;
          features = [ "raw" ];
        }];
        buildDependencies = [{
          name = "autocfg";
          packageId = "autocfg";
        }];
        features = {
          "rayon" = [ "dep:rayon" ];
          "rustc-rayon" = [ "dep:rustc-rayon" ];
          "serde" = [ "dep:serde" ];
          "serde-1" = [ "serde" ];
        };
        resolvedDefaultFeatures = [ "std" ];
      };
      "instrumentation-parent" = rec {
        crateName = "instrumentation-parent";
        version = "0.1.0";
        edition = "2018";
        crateBin = [
          {
            name = "tape-determinism-checker";
            path = "src/bin/tape-determinism-checker/main.rs";
          }
          {
            name = "instrumentation-parent";
            path = "src/bin/instrumentation-parent/main.rs";
          }
        ];
        src = lib.cleanSourceWith {
          filter = sourceFilter;
          src = ./.;
        };
        dependencies = [
          {
            name = "anyhow";
            packageId = "anyhow";
          }
          {
            name = "bstr";
            packageId = "bstr";
            features = [ "serde1" ];
          }
          {
            name = "clap";
            packageId = "clap";
            features = [ "derive" ];
          }
          {
            name = "log";
            packageId = "log";
          }
          {
            name = "nix";
            packageId = "nix";
          }
          {
            name = "serde";
            packageId = "serde";
            features = [ "derive" ];
          }
          {
            name = "serde_json";
            packageId = "serde_json";
          }
          {
            name = "stderrlog";
            packageId = "stderrlog";
          }
        ];

      };
      "itoa" = rec {
        crateName = "itoa";
        version = "1.0.1";
        edition = "2018";
        sha256 = "0d8wr2qf5b25a04xf10rz9r0pdbjdgb0zaw3xvf8k2sqcz1qzaqs";
        authors = [ "David Tolnay <dtolnay@gmail.com>" ];

      };
      "lazy_static" = rec {
        crateName = "lazy_static";
        version = "1.4.0";
        edition = "2015";
        sha256 = "0in6ikhw8mgl33wjv6q6xfrb5b9jr16q8ygjy803fay4zcisvaz2";
        authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
        features = {
          "spin" = [ "dep:spin" ];
          "spin_no_std" = [ "spin" ];
        };
      };
      "libc" = rec {
        crateName = "libc";
        version = "0.2.122";
        edition = "2015";
        sha256 = "0ngjp0kyzn1yl2sl61c9ds8id4lss7qf9kcbiki741xzw9kphr7c";
        authors = [ "The Rust Project Developers" ];
        features = {
          "default" = [ "std" ];
          "rustc-dep-of-std" = [ "align" "rustc-std-workspace-core" ];
          "rustc-std-workspace-core" = [ "dep:rustc-std-workspace-core" ];
          "use_std" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "default" "extra_traits" "std" ];
      };
      "log" = rec {
        crateName = "log";
        version = "0.4.17";
        edition = "2015";
        sha256 = "0biqlaaw1lsr8bpnmbcc0fvgjj34yy79ghqzyi0ali7vgil2xcdb";
        authors = [ "The Rust Project Developers" ];
        dependencies = [{
          name = "cfg-if";
          packageId = "cfg-if";
        }];
        features = {
          "kv_unstable" = [ "value-bag" ];
          "kv_unstable_serde" = [ "kv_unstable_std" "value-bag/serde" "serde" ];
          "kv_unstable_std" = [ "std" "kv_unstable" "value-bag/error" ];
          "kv_unstable_sval" = [ "kv_unstable" "value-bag/sval" "sval" ];
          "serde" = [ "dep:serde" ];
          "sval" = [ "dep:sval" ];
          "value-bag" = [ "dep:value-bag" ];
        };
        resolvedDefaultFeatures = [ "std" ];
      };
      "memchr" = rec {
        crateName = "memchr";
        version = "2.5.0";
        edition = "2018";
        sha256 = "0vanfk5mzs1g1syqnj03q8n0syggnhn55dq535h2wxr7rwpfbzrd";
        authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
        features = {
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "default" = [ "std" ];
          "libc" = [ "dep:libc" ];
          "rustc-dep-of-std" = [ "core" "compiler_builtins" ];
          "use_std" = [ "std" ];
        };
        resolvedDefaultFeatures = [ "std" ];
      };
      "memoffset" = rec {
        crateName = "memoffset";
        version = "0.6.5";
        edition = "2015";
        sha256 = "1kkrzll58a3ayn5zdyy9i1f1v3mx0xgl29x0chq614zazba638ss";
        authors = [ "Gilad Naaman <gilad.naaman@gmail.com>" ];
        buildDependencies = [{
          name = "autocfg";
          packageId = "autocfg";
        }];
        features = { };
        resolvedDefaultFeatures = [ "default" ];
      };
      "nix" = rec {
        crateName = "nix";
        version = "0.23.1";
        edition = "2018";
        sha256 = "1iimixk7y2qk0jswqich4mkd8kqyzdghcgy6203j8fmxmhbn71lz";
        authors = [ "The nix-rust Project Developers" ];
        dependencies = [
          {
            name = "bitflags";
            packageId = "bitflags";
          }
          {
            name = "cfg-if";
            packageId = "cfg-if";
          }
          {
            name = "libc";
            packageId = "libc";
            features = [ "extra_traits" ];
          }
          {
            name = "memoffset";
            packageId = "memoffset";
            target = { target, features }: (!(target."os" == "redox"));
          }
        ];
        buildDependencies = [{
          name = "cc";
          packageId = "cc";
          target = { target, features }: (target."os" == "dragonfly");
        }];

      };
      "num-integer" = rec {
        crateName = "num-integer";
        version = "0.1.45";
        edition = "2015";
        sha256 = "1ncwavvwdmsqzxnn65phv6c6nn72pnv9xhpmjd6a429mzf4k6p92";
        authors = [ "The Rust Project Developers" ];
        dependencies = [{
          name = "num-traits";
          packageId = "num-traits";
          usesDefaultFeatures = false;
        }];
        buildDependencies = [{
          name = "autocfg";
          packageId = "autocfg";
        }];
        features = {
          "default" = [ "std" ];
          "i128" = [ "num-traits/i128" ];
          "std" = [ "num-traits/std" ];
        };
      };
      "num-traits" = rec {
        crateName = "num-traits";
        version = "0.2.15";
        edition = "2015";
        sha256 = "1kfdqqw2ndz0wx2j75v9nbjx7d3mh3150zs4p5595y02rwsdx3jp";
        authors = [ "The Rust Project Developers" ];
        buildDependencies = [{
          name = "autocfg";
          packageId = "autocfg";
        }];
        features = {
          "default" = [ "std" ];
          "libm" = [ "dep:libm" ];
        };
      };
      "once_cell" = rec {
        crateName = "once_cell";
        version = "1.12.0";
        edition = "2018";
        sha256 = "09a2gb4sls2d3762jsps81s5y270465s0ip7cvv5h7qc7zwcw2bp";
        authors = [ "Aleksey Kladov <aleksey.kladov@gmail.com>" ];
        features = {
          "alloc" = [ "race" ];
          "atomic-polyfill" = [ "dep:atomic-polyfill" ];
          "default" = [ "std" ];
          "parking_lot" = [ "parking_lot_core" ];
          "parking_lot_core" = [ "dep:parking_lot_core" ];
          "std" = [ "alloc" ];
        };
        resolvedDefaultFeatures = [ "alloc" "default" "race" "std" ];
      };
      "os_str_bytes" = rec {
        crateName = "os_str_bytes";
        version = "6.1.0";
        edition = "2018";
        sha256 = "1ykav0kv9152z4cmv8smwmd9pac9q42sihi4wphnrzlwx4c6hci1";
        authors = [ "dylni" ];
        features = {
          "default" = [ "memchr" "raw_os_str" ];
          "memchr" = [ "dep:memchr" ];
          "print_bytes" = [ "dep:print_bytes" ];
          "uniquote" = [ "dep:uniquote" ];
        };
        resolvedDefaultFeatures = [ "raw_os_str" ];
      };
      "proc-macro-error" = rec {
        crateName = "proc-macro-error";
        version = "1.0.4";
        edition = "2018";
        sha256 = "1373bhxaf0pagd8zkyd03kkx6bchzf6g0dkwrwzsnal9z47lj9fs";
        authors = [ "CreepySkeleton <creepy-skeleton@yandex.ru>" ];
        dependencies = [
          {
            name = "proc-macro-error-attr";
            packageId = "proc-macro-error-attr";
          }
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
            optional = true;
            usesDefaultFeatures = false;
          }
        ];
        buildDependencies = [{
          name = "version_check";
          packageId = "version_check";
        }];
        features = {
          "default" = [ "syn-error" ];
          "syn" = [ "dep:syn" ];
          "syn-error" = [ "syn" ];
        };
        resolvedDefaultFeatures = [ "default" "syn" "syn-error" ];
      };
      "proc-macro-error-attr" = rec {
        crateName = "proc-macro-error-attr";
        version = "1.0.4";
        edition = "2018";
        sha256 = "0sgq6m5jfmasmwwy8x4mjygx5l7kp8s4j60bv25ckv2j1qc41gm1";
        procMacro = true;
        authors = [ "CreepySkeleton <creepy-skeleton@yandex.ru>" ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
        ];
        buildDependencies = [{
          name = "version_check";
          packageId = "version_check";
        }];

      };
      "proc-macro2" = rec {
        crateName = "proc-macro2";
        version = "1.0.37";
        edition = "2018";
        sha256 = "1ldg6l97xlr4dal4kmk0c4l8kn7nn8w1a17wd8hdlpwd8cc74xgc";
        authors = [
          "David Tolnay <dtolnay@gmail.com>"
          "Alex Crichton <alex@alexcrichton.com>"
        ];
        dependencies = [{
          name = "unicode-xid";
          packageId = "unicode-xid";
        }];
        features = { "default" = [ "proc-macro" ]; };
        resolvedDefaultFeatures = [ "default" "proc-macro" ];
      };
      "quote" = rec {
        crateName = "quote";
        version = "1.0.17";
        edition = "2018";
        sha256 = "0n1z06kngl0h24d4n6f1cv690js8rlbb92za6dps6x7qyyzh4bb3";
        authors = [ "David Tolnay <dtolnay@gmail.com>" ];
        dependencies = [{
          name = "proc-macro2";
          packageId = "proc-macro2";
          usesDefaultFeatures = false;
        }];
        features = {
          "default" = [ "proc-macro" ];
          "proc-macro" = [ "proc-macro2/proc-macro" ];
        };
        resolvedDefaultFeatures = [ "default" "proc-macro" ];
      };
      "regex-automata" = rec {
        crateName = "regex-automata";
        version = "0.1.10";
        edition = "2015";
        sha256 = "0ci1hvbzhrfby5fdpf4ganhf7kla58acad9i1ff1p34dzdrhs8vc";
        authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
        features = {
          "default" = [ "std" ];
          "fst" = [ "dep:fst" ];
          "regex-syntax" = [ "dep:regex-syntax" ];
          "std" = [ "regex-syntax" ];
          "transducer" = [ "std" "fst" ];
        };
      };
      "ryu" = rec {
        crateName = "ryu";
        version = "1.0.9";
        edition = "2018";
        sha256 = "17qlxkqm4h8h9xqj6rh2vnmwxyzikbsj5w223chmr5l2qx8bgd3k";
        authors = [ "David Tolnay <dtolnay@gmail.com>" ];
        features = { "no-panic" = [ "dep:no-panic" ]; };
      };
      "serde" = rec {
        crateName = "serde";
        version = "1.0.136";
        edition = "2015";
        sha256 = "12a791cbdd3gi08536i4frrqsps0ak8gvhpijvgj9rg1055y4cff";
        authors = [
          "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [{
          name = "serde_derive";
          packageId = "serde_derive";
          optional = true;
        }];
        devDependencies = [{
          name = "serde_derive";
          packageId = "serde_derive";
        }];
        features = {
          "default" = [ "std" ];
          "derive" = [ "serde_derive" ];
          "serde_derive" = [ "dep:serde_derive" ];
        };
        resolvedDefaultFeatures = [ "default" "derive" "serde_derive" "std" ];
      };
      "serde_derive" = rec {
        crateName = "serde_derive";
        version = "1.0.136";
        edition = "2015";
        sha256 = "1yb28smlymba4qbj2bn4c4myvblypqvkxv9q33s0dlzwa9qpwn88";
        procMacro = true;
        authors = [
          "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
          }
          {
            name = "quote";
            packageId = "quote";
          }
          {
            name = "syn";
            packageId = "syn";
          }
        ];
        features = { };
        resolvedDefaultFeatures = [ "default" ];
      };
      "serde_json" = rec {
        crateName = "serde_json";
        version = "1.0.79";
        edition = "2018";
        sha256 = "158xd1swdvw6y59bx4avb8vdpj727n54r77xw5f7c15kqfjrz3cf";
        authors = [
          "Erick Tryzelaar <erick.tryzelaar@gmail.com>"
          "David Tolnay <dtolnay@gmail.com>"
        ];
        dependencies = [
          {
            name = "itoa";
            packageId = "itoa";
          }
          {
            name = "ryu";
            packageId = "ryu";
          }
          {
            name = "serde";
            packageId = "serde";
            usesDefaultFeatures = false;
          }
        ];
        features = {
          "alloc" = [ "serde/alloc" ];
          "default" = [ "std" ];
          "indexmap" = [ "dep:indexmap" ];
          "preserve_order" = [ "indexmap" ];
          "std" = [ "serde/std" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "stderrlog" = rec {
        crateName = "stderrlog";
        version = "0.5.1";
        edition = "2018";
        sha256 = "0f2s2lfkjkjfn5w517zy6ffmpc2cw275w9m6mwcs151yzwp3x9a5";
        authors = [ "Doug Goldstein <cardoe@cardoe.com>" ];
        dependencies = [
          {
            name = "atty";
            packageId = "atty";
          }
          {
            name = "chrono";
            packageId = "chrono";
          }
          {
            name = "log";
            packageId = "log";
            features = [ "std" ];
          }
          {
            name = "termcolor";
            packageId = "termcolor";
          }
          {
            name = "thread_local";
            packageId = "thread_local";
          }
        ];

      };
      "strsim" = rec {
        crateName = "strsim";
        version = "0.10.0";
        edition = "2015";
        sha256 = "08s69r4rcrahwnickvi0kq49z524ci50capybln83mg6b473qivk";
        authors = [ "Danny Guo <danny@dannyguo.com>" ];

      };
      "syn" = rec {
        crateName = "syn";
        version = "1.0.91";
        edition = "2018";
        sha256 = "0kflvi0r456s42n3z0d5snilsab2q9ns0dkwnwwg9vn84nwb50xn";
        authors = [ "David Tolnay <dtolnay@gmail.com>" ];
        dependencies = [
          {
            name = "proc-macro2";
            packageId = "proc-macro2";
            usesDefaultFeatures = false;
          }
          {
            name = "quote";
            packageId = "quote";
            optional = true;
            usesDefaultFeatures = false;
          }
          {
            name = "unicode-xid";
            packageId = "unicode-xid";
          }
        ];
        features = {
          "default" =
            [ "derive" "parsing" "printing" "clone-impls" "proc-macro" ];
          "printing" = [ "quote" ];
          "proc-macro" = [ "proc-macro2/proc-macro" "quote/proc-macro" ];
          "quote" = [ "dep:quote" ];
          "test" = [ "syn-test-suite/all-features" ];
        };
        resolvedDefaultFeatures = [
          "clone-impls"
          "default"
          "derive"
          "full"
          "parsing"
          "printing"
          "proc-macro"
          "quote"
        ];
      };
      "termcolor" = rec {
        crateName = "termcolor";
        version = "1.1.3";
        edition = "2018";
        sha256 = "0mbpflskhnz3jf312k50vn0hqbql8ga2rk0k79pkgchip4q4vcms";
        authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
        dependencies = [{
          name = "winapi-util";
          packageId = "winapi-util";
          target = { target, features }: (target."windows" or false);
        }];

      };
      "textwrap" = rec {
        crateName = "textwrap";
        version = "0.15.0";
        edition = "2018";
        sha256 = "1yw513k61lfiwgqrfvsjw1a5wpvm0azhpjr2kr0jhnq9c56is55i";
        authors = [ "Martin Geisler <martin@geisler.net>" ];
        features = {
          "default" = [ "unicode-linebreak" "unicode-width" "smawk" ];
          "hyphenation" = [ "dep:hyphenation" ];
          "smawk" = [ "dep:smawk" ];
          "terminal_size" = [ "dep:terminal_size" ];
          "unicode-linebreak" = [ "dep:unicode-linebreak" ];
          "unicode-width" = [ "dep:unicode-width" ];
        };
      };
      "thread_local" = rec {
        crateName = "thread_local";
        version = "1.0.1";
        edition = "2015";
        sha256 = "054vlrr1vsdy1h4b7n99mr24pnj8928ig9qwzg36wnkld4dns36l";
        authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
        dependencies = [{
          name = "lazy_static";
          packageId = "lazy_static";
        }];

      };
      "time" = rec {
        crateName = "time";
        version = "0.1.44";
        edition = "2015";
        sha256 = "0m9jwy2pcmk232r3b9r80fs12mkckfjffjha4qfaxcdq9a8ydfbd";
        authors = [ "The Rust Project Developers" ];
        dependencies = [
          {
            name = "libc";
            packageId = "libc";
          }
          {
            name = "wasi";
            packageId = "wasi";
            target = { target, features }: (target."os" == "wasi");
          }
          {
            name = "winapi";
            packageId = "winapi";
            target = { target, features }: (target."windows" or false);
            features = [
              "std"
              "minwinbase"
              "minwindef"
              "ntdef"
              "profileapi"
              "sysinfoapi"
              "timezoneapi"
            ];
          }
        ];
        devDependencies = [{
          name = "winapi";
          packageId = "winapi";
          features = [ "std" "processthreadsapi" "winbase" ];
        }];
        features = { "rustc-serialize" = [ "dep:rustc-serialize" ]; };
      };
      "unicode-xid" = rec {
        crateName = "unicode-xid";
        version = "0.2.2";
        edition = "2015";
        sha256 = "1wrkgcw557v311dkdb6n2hrix9dm2qdsb1zpw7pn79l03zb85jwc";
        authors = [
          "erick.tryzelaar <erick.tryzelaar@gmail.com>"
          "kwantam <kwantam@gmail.com>"
          "Manish Goregaokar <manishsmail@gmail.com>"
        ];
        features = { };
        resolvedDefaultFeatures = [ "default" ];
      };
      "version_check" = rec {
        crateName = "version_check";
        version = "0.9.4";
        edition = "2015";
        sha256 = "0gs8grwdlgh0xq660d7wr80x14vxbizmd8dbp29p2pdncx8lp1s9";
        authors = [ "Sergio Benitez <sb@sergio.bz>" ];

      };
      "wasi" = rec {
        crateName = "wasi";
        version = "0.10.0+wasi-snapshot-preview1";
        edition = "2018";
        sha256 = "07y3l8mzfzzz4cj09c8y90yak4hpsi9g7pllyzpr6xvwrabka50s";
        authors = [ "The Cranelift Project Developers" ];
        features = {
          "compiler_builtins" = [ "dep:compiler_builtins" ];
          "core" = [ "dep:core" ];
          "default" = [ "std" ];
          "rustc-dep-of-std" =
            [ "compiler_builtins" "core" "rustc-std-workspace-alloc" ];
          "rustc-std-workspace-alloc" = [ "dep:rustc-std-workspace-alloc" ];
        };
        resolvedDefaultFeatures = [ "default" "std" ];
      };
      "winapi" = rec {
        crateName = "winapi";
        version = "0.3.9";
        edition = "2015";
        sha256 = "06gl025x418lchw1wxj64ycr7gha83m44cjr5sarhynd9xkrm0sw";
        authors = [ "Peter Atashian <retep998@gmail.com>" ];
        dependencies = [
          {
            name = "winapi-i686-pc-windows-gnu";
            packageId = "winapi-i686-pc-windows-gnu";
            target = { target, features }:
              (stdenv.hostPlatform.config == "i686-pc-windows-gnu");
          }
          {
            name = "winapi-x86_64-pc-windows-gnu";
            packageId = "winapi-x86_64-pc-windows-gnu";
            target = { target, features }:
              (stdenv.hostPlatform.config == "x86_64-pc-windows-gnu");
          }
        ];
        features = { "debug" = [ "impl-debug" ]; };
        resolvedDefaultFeatures = [
          "consoleapi"
          "errhandlingapi"
          "fileapi"
          "minwinbase"
          "minwindef"
          "ntdef"
          "processenv"
          "profileapi"
          "std"
          "sysinfoapi"
          "timezoneapi"
          "winbase"
          "wincon"
          "winerror"
          "winnt"
        ];
      };
      "winapi-i686-pc-windows-gnu" = rec {
        crateName = "winapi-i686-pc-windows-gnu";
        version = "0.4.0";
        edition = "2015";
        sha256 = "1dmpa6mvcvzz16zg6d5vrfy4bxgg541wxrcip7cnshi06v38ffxc";
        authors = [ "Peter Atashian <retep998@gmail.com>" ];

      };
      "winapi-util" = rec {
        crateName = "winapi-util";
        version = "0.1.5";
        edition = "2018";
        sha256 = "0y71bp7f6d536czj40dhqk0d55wfbbwqfp2ymqf1an5ibgl6rv3h";
        authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
        dependencies = [{
          name = "winapi";
          packageId = "winapi";
          target = { target, features }: (target."windows" or false);
          features = [
            "std"
            "consoleapi"
            "errhandlingapi"
            "fileapi"
            "minwindef"
            "processenv"
            "winbase"
            "wincon"
            "winerror"
            "winnt"
          ];
        }];

      };
      "winapi-x86_64-pc-windows-gnu" = rec {
        crateName = "winapi-x86_64-pc-windows-gnu";
        version = "0.4.0";
        edition = "2015";
        sha256 = "0gqq64czqb64kskjryj8isp62m2sgvx25yyj3kpc2myh85w24bki";
        authors = [ "Peter Atashian <retep998@gmail.com>" ];

      };
    };

    #
    # crate2nix/default.nix (excerpt start)
    #

    /* Target (platform) data for conditional dependencies.
       This corresponds roughly to what buildRustCrate is setting.
    */
    defaultTarget = {
      unix = true;
      windows = false;
      fuchsia = true;
      test = false;

      # This doesn't appear to be officially documented anywhere yet.
      # See https://github.com/rust-lang-nursery/rust-forge/issues/101.
      os = if stdenv.hostPlatform.isDarwin then
        "macos"
      else
        stdenv.hostPlatform.parsed.kernel.name;
      arch = stdenv.hostPlatform.parsed.cpu.name;
      family = "unix";
      env = "gnu";
      endian = if stdenv.hostPlatform.parsed.cpu.significantByte.name
      == "littleEndian" then
        "little"
      else
        "big";
      pointer_width = toString stdenv.hostPlatform.parsed.cpu.bits;
      vendor = stdenv.hostPlatform.parsed.vendor.name;
      debug_assertions = false;
    };

    # Filters common temp files and build files.
    # TODO(pkolloch): Substitute with gitignore filter
    sourceFilter = name: type:
      let baseName = builtins.baseNameOf (builtins.toString name);
      in !(
        # Filter out git
        baseName == ".gitignore" || (type == "directory" && baseName == ".git")

        # Filter out build results
        || (type == "directory" && (baseName == "target" || baseName == "_site"
          || baseName == ".sass-cache" || baseName == ".jekyll-metadata"
          || baseName == "build-artifacts"))

        # Filter out nix-build result symlinks
        || (type == "symlink" && lib.hasPrefix "result" baseName)

        # Filter out IDE config
        || (type == "directory"
          && (baseName == ".idea" || baseName == ".vscode"))
        || lib.hasSuffix ".iml" baseName

        # Filter out nix build files
        || baseName == "Cargo.nix"

        # Filter out editor backup / swap files.
        || lib.hasSuffix "~" baseName || builtins.match "^\\.sw[a-z]$$" baseName
        != null || builtins.match "^\\..*\\.sw[a-z]$$" baseName != null
        || lib.hasSuffix ".tmp" baseName || lib.hasSuffix ".bak" baseName
        || baseName == "tests.nix");

    /* Returns a crate which depends on successful test execution
       of crate given as the second argument.

       testCrateFlags: list of flags to pass to the test exectuable
       testInputs: list of packages that should be available during test execution
    */
    crateWithTest =
      { crate, testCrate, testCrateFlags, testInputs, testPreRun, testPostRun }:
      assert builtins.typeOf testCrateFlags == "list";
      assert builtins.typeOf testInputs == "list";
      assert builtins.typeOf testPreRun == "string";
      assert builtins.typeOf testPostRun == "string";
      let
        # override the `crate` so that it will build and execute tests instead of
        # building the actual lib and bin targets We just have to pass `--test`
        # to rustc and it will do the right thing.  We execute the tests and copy
        # their log and the test executables to $out for later inspection.
        test = let
          drv = testCrate.override (_: { buildTests = true; });
          # If the user hasn't set any pre/post commands, we don't want to
          # insert empty lines. This means that any existing users of crate2nix
          # don't get a spurious rebuild unless they set these explicitly.
          testCommand = pkgs.lib.concatStringsSep "\n"
            (pkgs.lib.filter (s: s != "") [
              testPreRun
              "$f $testCrateFlags 2>&1 | tee -a $out"
              testPostRun
            ]);
        in pkgs.runCommand "run-tests-${testCrate.name}" {
          inherit testCrateFlags;
          buildInputs = testInputs;
        } ''
          set -ex

          export RUST_BACKTRACE=1

          # recreate a file hierarchy as when running tests with cargo

          # the source for test data
          ${pkgs.xorg.lndir}/bin/lndir ${crate.src}

          # build outputs
          testRoot=target/debug
          mkdir -p $testRoot

          # executables of the crate
          # we copy to prevent std::env::current_exe() to resolve to a store location
          for i in ${crate}/bin/*; do
            cp "$i" "$testRoot"
          done
          chmod +w -R .

          # test harness executables are suffixed with a hash, like cargo does
          # this allows to prevent name collision with the main
          # executables of the crate
          hash=$(basename $out)
          for file in ${drv}/tests/*; do
            f=$testRoot/$(basename $file)-$hash
            cp $file $f
            ${testCommand}
          done
        '';
      in pkgs.runCommand "${crate.name}-linked" {
        inherit (crate) outputs crateName;
        passthru = (crate.passthru or { }) // { inherit test; };
      } ''
        echo tested by ${test}
        ${lib.concatMapStringsSep "\n"
        (output: "ln -s ${crate.${output}} ${"$"}${output}") crate.outputs}
      '';

    # A restricted overridable version of builtRustCratesWithFeatures.
    buildRustCrateWithFeatures = { packageId, features ? rootFeatures
      , crateOverrides ? defaultCrateOverrides, buildRustCrateForPkgsFunc ? null
      , runTests ? false, testCrateFlags ? [ ], testInputs ? [ ]
        # Any command to run immediatelly before a test is executed.
      , testPreRun ? ""
        # Any command run immediatelly after a test is executed.
      , testPostRun ? "" }:
      lib.makeOverridable ({ features, crateOverrides, runTests, testCrateFlags
        , testInputs, testPreRun, testPostRun }:
        let
          buildRustCrateForPkgsFuncOverriden =
            if buildRustCrateForPkgsFunc != null then
              buildRustCrateForPkgsFunc
            else
              (if crateOverrides == pkgs.defaultCrateOverrides then
                buildRustCrateForPkgs
              else
                pkgs:
                (buildRustCrateForPkgs pkgs).override {
                  defaultCrateOverrides = crateOverrides;
                });
          builtRustCrates = builtRustCratesWithFeatures {
            inherit packageId features;
            buildRustCrateForPkgsFunc = buildRustCrateForPkgsFuncOverriden;
            runTests = false;
          };
          builtTestRustCrates = builtRustCratesWithFeatures {
            inherit packageId features;
            buildRustCrateForPkgsFunc = buildRustCrateForPkgsFuncOverriden;
            runTests = true;
          };
          drv = builtRustCrates.crates.${packageId};
          testDrv = builtTestRustCrates.crates.${packageId};
          derivation = if runTests then
            crateWithTest {
              crate = drv;
              testCrate = testDrv;
              inherit testCrateFlags testInputs testPreRun testPostRun;
            }
          else
            drv;
        in derivation) {
          inherit features crateOverrides runTests testCrateFlags testInputs
            testPreRun testPostRun;
        };

    /* Returns an attr set with packageId mapped to the result of buildRustCrateForPkgsFunc
       for the corresponding crate.
    */
    builtRustCratesWithFeatures = { packageId, features, crateConfigs ? crates
      , buildRustCrateForPkgsFunc, runTests, target ? defaultTarget }@args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isList features);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests);
      let
        rootPackageId = packageId;
        mergedFeatures = mergePackageFeatures (args // {
          inherit rootPackageId;
          target = target // { test = runTests; };
        });
        # Memoize built packages so that reappearing packages are only built once.
        builtByPackageIdByPkgs = mkBuiltByPackageIdByPkgs pkgs;
        mkBuiltByPackageIdByPkgs = pkgs:
          let
            self = {
              crates = lib.mapAttrs (packageId: value:
                buildByPackageIdForPkgsImpl self pkgs packageId) crateConfigs;
              build = mkBuiltByPackageIdByPkgs pkgs.buildPackages;
            };
          in self;
        buildByPackageIdForPkgsImpl = self: pkgs: packageId:
          let
            features = mergedFeatures."${packageId}" or [ ];
            crateConfig' = crateConfigs."${packageId}";
            crateConfig = builtins.removeAttrs crateConfig' [
              "resolvedDefaultFeatures"
              "devDependencies"
            ];
            devDependencies =
              lib.optionals (runTests && packageId == rootPackageId)
              (crateConfig'.devDependencies or [ ]);
            dependencies = dependencyDerivations {
              inherit features target;
              buildByPackageId = depPackageId:
                # proc_macro crates must be compiled for the build architecture
                if crateConfigs.${depPackageId}.procMacro or false then
                  self.build.crates.${depPackageId}
                else
                  self.crates.${depPackageId};
              dependencies = (crateConfig.dependencies or [ ])
                ++ devDependencies;
            };
            buildDependencies = dependencyDerivations {
              inherit features target;
              buildByPackageId = depPackageId:
                self.build.crates.${depPackageId};
              dependencies = crateConfig.buildDependencies or [ ];
            };
            filterEnabledDependenciesForThis = dependencies:
              filterEnabledDependencies {
                inherit dependencies features target;
              };
            dependenciesWithRenames = lib.filter (d: d ? "rename")
              (filterEnabledDependenciesForThis
                ((crateConfig.buildDependencies or [ ])
                  ++ (crateConfig.dependencies or [ ]) ++ devDependencies));
            # Crate renames have the form:
            #
            # {
            #    crate_name = [
            #       { version = "1.2.3"; rename = "crate_name01"; }
            #    ];
            #    # ...
            # }
            crateRenames = let
              grouped = lib.groupBy (dependency: dependency.name)
                dependenciesWithRenames;
              versionAndRename = dep:
                let package = crateConfigs."${dep.packageId}";
                in {
                  inherit (dep) rename;
                  version = package.version;
                };
            in lib.mapAttrs
            (name: choices: builtins.map versionAndRename choices) grouped;
          in buildRustCrateForPkgsFunc pkgs (crateConfig // {
            src = crateConfig.src or (pkgs.fetchurl rec {
              name = "${crateConfig.crateName}-${crateConfig.version}.tar.gz";
              # https://www.pietroalbini.org/blog/downloading-crates-io/
              # Not rate-limited, CDN URL.
              url =
                "https://static.crates.io/crates/${crateConfig.crateName}/${crateConfig.crateName}-${crateConfig.version}.crate";
              sha256 = assert (lib.assertMsg (crateConfig ? sha256)
                "Missing sha256 for ${name}");
                crateConfig.sha256;
            });
            extraRustcOpts = lib.lists.optional (targetFeatures != [ ])
              "-C target-feature=${
                lib.concatMapStringsSep "," (x: "+${x}") targetFeatures
              }";
            inherit features dependencies buildDependencies crateRenames
              release;
          });
      in builtByPackageIdByPkgs;

    # Returns the actual derivations for the given dependencies.
    dependencyDerivations =
      { buildByPackageId, features, dependencies, target }:
      assert (builtins.isList features);
      assert (builtins.isList dependencies);
      assert (builtins.isAttrs target);
      let
        enabledDependencies =
          filterEnabledDependencies { inherit dependencies features target; };
        depDerivation = dependency: buildByPackageId dependency.packageId;
      in map depDerivation enabledDependencies;

    /* Returns a sanitized version of val with all values substituted that cannot
       be serialized as JSON.
    */
    sanitizeForJson = val:
      if builtins.isAttrs val then
        lib.mapAttrs (n: v: sanitizeForJson v) val
      else if builtins.isList val then
        builtins.map sanitizeForJson val
      else if builtins.isFunction val then
        "function"
      else
        val;

    # Returns various tools to debug a crate.
    debugCrate = { packageId, target ? defaultTarget }:
      assert (builtins.isString packageId);
      let
        debug = rec {
          # The built tree as passed to buildRustCrate.
          buildTree = buildRustCrateWithFeatures {
            buildRustCrateForPkgsFunc = _: lib.id;
            inherit packageId;
          };
          sanitizedBuildTree = sanitizeForJson buildTree;
          dependencyTree = sanitizeForJson (buildRustCrateWithFeatures {
            buildRustCrateForPkgsFunc = _: crate: {
              "01_crateName" = crate.crateName or false;
              "02_features" = crate.features or [ ];
              "03_dependencies" = crate.dependencies or [ ];
            };
            inherit packageId;
          });
          mergedPackageFeatures = mergePackageFeatures {
            features = rootFeatures;
            inherit packageId target;
          };
          diffedDefaultPackageFeatures =
            diffDefaultPackageFeatures { inherit packageId target; };
        };
      in { internal = debug; };

    /* Returns differences between cargo default features and crate2nix default
       features.

       This is useful for verifying the feature resolution in crate2nix.
    */
    diffDefaultPackageFeatures = { crateConfigs ? crates, packageId, target }:
      assert (builtins.isAttrs crateConfigs);
      let
        prefixValues = prefix: lib.mapAttrs (n: v: { "${prefix}" = v; });
        mergedFeatures = prefixValues "crate2nix" (mergePackageFeatures {
          inherit crateConfigs packageId target;
          features = [ "default" ];
        });
        configs = prefixValues "cargo" crateConfigs;
        combined = lib.foldAttrs (a: b: a // b) { } [ mergedFeatures configs ];
        onlyInCargo = builtins.attrNames
          (lib.filterAttrs (n: v: !(v ? "crate2nix") && (v ? "cargo"))
            combined);
        onlyInCrate2Nix = builtins.attrNames
          (lib.filterAttrs (n: v: (v ? "crate2nix") && !(v ? "cargo"))
            combined);
        differentFeatures = lib.filterAttrs (n: v:
          (v ? "crate2nix") && (v ? "cargo") && (v.crate2nix.features or [ ])
          != (v."cargo".resolved_default_features or [ ])) combined;
      in builtins.toJSON {
        inherit onlyInCargo onlyInCrate2Nix differentFeatures;
      };

    /* Returns an attrset mapping packageId to the list of enabled features.

       If multiple paths to a dependency enable different features, the
       corresponding feature sets are merged. Features in rust are additive.
    */
    mergePackageFeatures = { crateConfigs ? crates, packageId
      , rootPackageId ? packageId, features ? rootFeatures
      , dependencyPath ? [ crates.${packageId}.crateName ]
      , featuresByPackageId ? { }, target
      # Adds devDependencies to the crate with rootPackageId.
      , runTests ? false, ... }@args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isString rootPackageId);
      assert (builtins.isList features);
      assert (builtins.isList dependencyPath);
      assert (builtins.isAttrs featuresByPackageId);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests);
      let
        crateConfig = crateConfigs."${packageId}" or (builtins.throw
          "Package not found: ${packageId}");
        expandedFeatures =
          expandFeatures (crateConfig.features or { }) features;
        enabledFeatures =
          enableFeatures (crateConfig.dependencies or [ ]) expandedFeatures;
        depWithResolvedFeatures = dependency:
          let
            packageId = dependency.packageId;
            features = dependencyFeatures enabledFeatures dependency;
          in { inherit packageId features; };
        resolveDependencies = cache: path: dependencies:
          assert (builtins.isAttrs cache);
          assert (builtins.isList dependencies);
          let
            enabledDependencies = filterEnabledDependencies {
              inherit dependencies target;
              features = enabledFeatures;
            };
            directDependencies =
              map depWithResolvedFeatures enabledDependencies;
            foldOverCache = op: lib.foldl op cache directDependencies;
          in foldOverCache (cache:
            { packageId, features }:
            let
              cacheFeatures = cache.${packageId} or [ ];
              combinedFeatures = sortedUnique (cacheFeatures ++ features);
            in if cache ? ${packageId} && cache.${packageId}
            == combinedFeatures then
              cache
            else
              mergePackageFeatures {
                features = combinedFeatures;
                featuresByPackageId = cache;
                inherit crateConfigs packageId target runTests rootPackageId;
              });
        cacheWithSelf = let
          cacheFeatures = featuresByPackageId.${packageId} or [ ];
          combinedFeatures = sortedUnique (cacheFeatures ++ enabledFeatures);
        in featuresByPackageId // { "${packageId}" = combinedFeatures; };
        cacheWithDependencies = resolveDependencies cacheWithSelf "dep"
          (crateConfig.dependencies or [ ]
            ++ lib.optionals (runTests && packageId == rootPackageId)
            (crateConfig.devDependencies or [ ]));
        cacheWithAll = resolveDependencies cacheWithDependencies "build"
          (crateConfig.buildDependencies or [ ]);
      in cacheWithAll;

    # Returns the enabled dependencies given the enabled features.
    filterEnabledDependencies = { dependencies, features, target }:
      assert (builtins.isList dependencies);
      assert (builtins.isList features);
      assert (builtins.isAttrs target);

      lib.filter (dep:
        let targetFunc = dep.target or (features: true);
        in targetFunc { inherit features target; } && (!(dep.optional or false)
          || builtins.any (doesFeatureEnableDependency dep) features))
      dependencies;

    # Returns whether the given feature should enable the given dependency.
    doesFeatureEnableDependency = { name, rename ? null, ... }:
      feature:
      let
        prefix = "${name}/";
        len = builtins.stringLength prefix;
        startsWithPrefix = builtins.substring 0 len feature == prefix;
      in (rename == null && feature == name)
      || (rename != null && rename == feature) || startsWithPrefix;

    /* Returns the expanded features for the given inputFeatures by applying the
       rules in featureMap.

       featureMap is an attribute set which maps feature names to lists of further
       feature names to enable in case this feature is selected.
    */
    expandFeatures = featureMap: inputFeatures:
      assert (builtins.isAttrs featureMap);
      assert (builtins.isList inputFeatures);
      let
        expandFeature = feature:
          assert (builtins.isString feature);
          [ feature ]
          ++ (expandFeatures featureMap (featureMap."${feature}" or [ ]));
        outFeatures = lib.concatMap expandFeature inputFeatures;
      in sortedUnique outFeatures;

    /* This function adds optional dependencies as features if they are enabled
       indirectly by dependency features. This function mimics Cargo's behavior
       described in a note at:
       https://doc.rust-lang.org/nightly/cargo/reference/features.html#dependency-features
    */
    enableFeatures = dependencies: features:
      assert (builtins.isList features);
      assert (builtins.isList dependencies);
      let
        additionalFeatures = lib.concatMap (dependency:
          assert (builtins.isAttrs dependency);
          let
            enabled =
              builtins.any (doesFeatureEnableDependency dependency) features;
          in if (dependency.optional or false) && enabled then
            [ dependency.name ]
          else
            [ ]) dependencies;
      in sortedUnique (features ++ additionalFeatures);

    /* Returns the actual features for the given dependency.

       features: The features of the crate that refers this dependency.
    */
    dependencyFeatures = features: dependency:
      assert (builtins.isList features);
      assert (builtins.isAttrs dependency);
      let
        defaultOrNil =
          if dependency.usesDefaultFeatures or true then [ "default" ] else [ ];
        explicitFeatures = dependency.features or [ ];
        additionalDependencyFeatures = let
          dependencyPrefix = (dependency.rename or dependency.name) + "/";
          dependencyFeatures =
            builtins.filter (f: lib.hasPrefix dependencyPrefix f) features;
        in builtins.map (lib.removePrefix dependencyPrefix) dependencyFeatures;
      in defaultOrNil ++ explicitFeatures ++ additionalDependencyFeatures;

    # Sorts and removes duplicates from a list of strings.
    sortedUnique = features:
      assert (builtins.isList features);
      assert (builtins.all builtins.isString features);
      let
        outFeaturesSet =
          lib.foldl (set: feature: set // { "${feature}" = 1; }) { } features;
        outFeaturesUnique = builtins.attrNames outFeaturesSet;
      in builtins.sort (a: b: a < b) outFeaturesUnique;

    deprecationWarning = message: value:
      if strictDeprecation then
        builtins.throw "strictDeprecation enabled, aborting: ${message}"
      else
        builtins.trace message value;

    #
    # crate2nix/default.nix (excerpt end)
    #
  };
}
